### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by xatoneaw** [jaredhaight/PSAttack#12]
the whole shell would crash randomly.

Invoke-mimikatz Keeps crashing before command completion
Will attach crash data was the normal c# instance of an object not .....

**Comment by jaredhaight** [comment]
Thanks xantoneaw. In addition to that crash data, if you could also include
details on operating system and the output of "$debug", that would be super
helpful.

Thanks!

**Comment by jaredhaight** [comment]
Hey xantoneaw, 

I'm going to ahead and close this issue, if you can reproduce the bug and get me the error message please re-open.

Thanks!
