### ISSUE TITLE
Crash on up-arrow, left-arrow (to edit a previous line)

### ISSUE THREAD

**Issue by FrackMacker** [jaredhaight/PSAttack#14]
Greetings!  When using left arrow key within PSAttack when using "Invoke-NinjaCopy" to change a value (-CompuerName in my case to attack multiple DC's), I get the following error:

C:\Users\REPLACED\Desktop #> Invoke-NinjaCopy -Path "C:\windows\ntds\ntds.dit"
-ComputerName REPLACED -LocalDestination "C:\Users\REPLACED\Desktop\REPLACED.dit.t
t"
Unhandled Exception: System.ArgumentOutOfRangeException: The value must be greaer than or equal to zero and less than the console's buffer size in that dimenson.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at PSAttack.Utils.Display.Output(AttackState attackState)
   at PSAttack.Program.Main(String[] args)

**Comment by jaredhaight** [comment]
This issue is related to cursor positioning on text that wraps the screen. Need to come up with a better way to calculate where the cursor should be.
