### ISSUE TITLE
.NET Depencies?

### ISSUE THREAD

**Issue by vysec** [jaredhaight/PSAttack#15]
Is there any plans to make this independent of .NET at some point? I have realised that if .NET or PowerShell is application whitelist blocked on a machine, PSPunch will not work.

**Comment by jaredhaight** [comment]
This would be SUPER cool, but it'd require basically rewriting the scripting host for PowerShell. It'd be a massive undertaking and not really in scope with this project. Awesome idea though, thanks for reaching out!
