### ISSUE TITLE
Chocolatey Package?

### ISSUE THREAD

**Issue by TerribleDev** [jaredhaight/PSAttack#20]
Think you can make this a [Chocolatey Package](https://chocolatey.org/) (apt-get on windows)? I don't mind helping you get it going.

Basically the advantage would be 2 fold:
1. people could just `choco install psattack` from their shells
2. updating would just be `choco update psattack` to update their versions

**Comment by jaredhaight** [comment]
Thanks for the idea, I'll look into it and see if it's a good fit for the project. Do you know of any example packages that pull from github repos? I did some real quick googling but didn't find anything.

**Comment by PashaPasta** [comment]
I believe that atom’s chocolatey package pulls from github.

**Comment by TerribleDev** [comment]
@jaredhaight  something like appveyor can do it pretty easily. appveyor has an environment variable that tells you if the current build has a tag for the sha you are building.

http://www.appveyor.com/docs/deployment#deploy-on-tag-github-and-gitlab-only

you could easily pack/push a package if that variable is set. 

https://github.com/TerribleDev/QuikPak/blob/master/build.cmd

all you need is a nuspec file
https://github.com/TerribleDev/QuikPak/blob/master/QuikPak/choco/quikpak.nuspec

and some commands to push it
`choco push ./path/to/yourpkg -apiKey %Secure_Variable_Here%`


you can just place your exe, and files in the root of the package and chocolatey will automatically add those to your path.

My example isn't totally ci'd (like the version is not set, nor the package is pushed by the current tag), but my project was beyond simple, and I was too lazy. That being said it is 100% feasible to do so..

**Comment by jaredhaight** [comment]
Closing this for now. Might revisit in the future. Thanks for the suggestion!
