### ISSUE TITLE
AV is detecting PS>Attack

### ISSUE THREAD

**Issue by jaredhaight** [jaredhaight/PSAttack#21]
Windows Defender (and maybe others) are detecting PS>Attack now. Need to figure out what they're tripping on and implement obfuscation to address that and future possible detections.

**Comment by jaredhaight** [comment]
Adding #23 from @nullbites as a comment here:

1) To defeat heuristic based AV you could try and implement the following as an option

if(cpu_cores < 1) { exit(); }
2) You can also include random do-nothing functions in builds as well and vary the levels of optimization.

3) Implementing string XORing/encryption with a random value created at build time may also work.

I'll do a pull later and try and implement some of these. I'll also start working on that 's/Console/Socket/g' idea we had for the networking functionality.

**Comment by curi0usJack** [comment]
I saw specifically that AV is flagging on the payloads as they get decrypted. Recommend running through Invoke-Obfuscation.

**Comment by jaredhaight** [comment]
Hrm.. do you know which AV caught it decrypting?

**Comment by curi0usJack** [comment]
Windows Defender. After compiling and when first loading.

[image: Inline image 2]


[image: Inline image 1]
