### ISSUE TITLE
Recomendations for AV evasion

### ISSUE THREAD

**Issue by nullbites** [jaredhaight/PSAttack#23]
1) To defeat heuristic based AV you could try and implement the following as an option  

- `if(cpu_cores < 1) { exit(); }`

2) You can also include random do-nothing functions in builds as well and vary the levels of optimization. 

3) Implementing string XORing/encryption with a random value created at build time may also work.

I'll do a pull later and try and implement some of these. I'll also start working on that 's/Console/Socket/g' idea we had for the networking functionality.

**Comment by jaredhaight** [comment]
Closing this and adding it as a comment on #21
