### ISSUE TITLE
ArgumentOutOfRangeException in System.Console.SetCursorPosition

### ISSUE THREAD

**Issue by BlueSkeye** [jaredhaight/PSAttack#26]
### Scenario

Using commit df3afc8
Copy PSAttack.exe in a folder having Path.Length > Console.WindowWidth
Launch PSAttacke.exe
### Witnessed behaviour

Stack trace (sanitized)

System.Console.SetCursorPosition(Int32 left, Int32 top)
PSAttack.Utils.Display.Output(AttackState attackState) @ Utils\Display.cs (line 34)
PSAttack.Program.Main(String[] args) @ Program.cs (line 151)

**Comment by jaredhaight** [comment]
Wow, this is a great issue submission. Thank you so much for the research on this.
