### ISSUE TITLE
is it still detect bu windows defender and av..if yes what is the solution?

### ISSUE THREAD

**Issue by mateo24xx** [jaredhaight/PSAttack#37]
i receive no connection after agent was download ,i think it was killed by av or windows defender..
i read in issue that it was fixed ..can you tell me more please?
thanks

**Comment by jaredhaight** [comment]
I'm not sure what you mean by "connection from agent". PS>Attack is a console application, theres no connection to be made.

**Comment by mateo24xx** [comment]
Hi jared ..sorrry this was not for you but for another tool  (dropboxC2)
